name: Magento

on: [push]

jobs:
  Shop:
    runs-on: ubuntu-18.04
    services:
      mariadb:
        image: docker.io/bitnami/mariadb:10.3
        env:
          ALLOW_EMPTY_PASSWORD: yes
          MARIADB_USER: bn_magento
          MARIADB_DATABASE: bitnami_magento
      magento:
        image: docker.io/bitnami/magento:2
        options: "--name magento"
        ports:
          - "80:8080"
          - "443:8443"
        env:
          MAGENTO_HOST: localhost
          MAGENTO_DATABASE_HOST: mariadb
          MAGENTO_DATABASE_PORT_NUMBER: 3306
          MAGENTO_DATABASE_USER: bn_magento
          MAGENTO_DATABASE_NAME: bitnami_magento
          ELASTICSEARCH_HOST: elasticsearch
          ELASTICSEARCH_PORT_NUMBER: 9200
          ALLOW_EMPTY_PASSWORD: yes
      elasticsearch:
        image: docker.io/bitnami/elasticsearch:6
    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Start ngrok
        run: |
          npm install ngrok &>/dev/null
          ls -l
          echo "::set-output name=host::$(bash CI/scripts/ngrok.sh ${{ secrets.NGROK_TOKEN }})"
        id: ngrok

      - name: Modify Magento
        run: |
          docker ps
          bash CI/scripts/modify_magento.sh ${{ steps.ngrok.outputs.host }}

      - name: Run test
        run: curl -L https://${{ steps.ngrok.outputs.host }}

      - name: Wait for 5 minutes
        run: sleep 5m
